travis:
  secure:
    BINSTAR_TOKEN: L/IkAlmBL1C2NvUmZYvl4spLykNfac759Rf4IEkNPehpe2b7SUQJoBH3O0g/G9MnVOOJ6t0qnYwrhzxAq3Vbr+WTjvKtepLm0rcmJm68CYhZ4yoSptm7nFEywpTtsvD2dPpLX3xp8rO9hDYyXOGxzD/sfNLqbf+6Qxahob7bP/S0BPmUioJTjqBsFs/GutXkpAVcnt2WtIVS/I2nXCc5ESVLUuPAioIgQlQ2irqgP4De2SzA/2beqWSOQiIIPEAHHU65AiBodr2+tiR9HkS7v5P+xAu2tAN/4xK1TU3sX7uY9xAGsQL4cw3NthqCImuWeP1fMrEJvr1Yk9FUMF+55/U0UfdNUN5Kjnsg+/ciA8tUZL/6sP7MItje9KHum95nNd7mEiZ4ULcLj1/k57QR7XnhM8ch3XHUTZ2eooPH11l1NL5P0vp7dVMiCyOraIiphcQpw1dH5FFGD2QkrS8QIL3axmp+n0JpfNGP7MUakNOgGNHNd38Has3rcZa3OBUkcf+5USHYzqI+mY8Qtebf+cLJy0PWhCEMPsE/Xq4/6vF4u+YoumFg+Ymk1jmj0M0hA9ktsgW4QRO9owaOvOUdaxdWj+tsggX5OHG2bgio4N21JMWT7X3FQdqq301HxFjJHeYFlNdqpb8TLSj8kcCxqX9IVKAR+cMPJgrijo+OLX0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
